platform :ios, '15.0'
use_frameworks!

def shared_pods
    pod 'MBProgressHUD', '~> 1.2.0'
    pod 'Masonry', '~> 1.1.0'
end

target 'DHBleSDKDemo' do
    shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |t|
        t.build_configurations.each do |c|
            c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        end
    end
end
